<a href="https://colab.research.google.com/github/RajuMekala01/ev_project/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numpy importing here

In [2]:
import numpy as np

arange for in a range of elements in array in np

In [3]:
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


properties of numpy
array in np for creating a array in numpy
shape is used to find array rows,columns
dtype is datatype for array

In [ ]:
new_arr=np.array([1,2,3,4,5])
print(new_arr)
print(new_arr[0])

[1 2 3 4 5]
1


In [ ]:
new_arr2=np.array([[1,2,3],
                  [4,5,6],
                  [6,7,8]])
print(new_arr2)
print(new_arr2.shape)

[[1 2 3]
 [4 5 6]
 [6 7 8]]
(3, 3)


In [ ]:
arr3=np.array([1.1,2.2,3.3],dtype=np.int64)
print(arr3)
print(arr3.dtype)

[1 2 3]
int64


In [ ]:
arr3d=np.zeros((2,3,4))
print(arr3d)
print("size of an array:",arr3d.size)
print("size of each element in array:",arr3d.itemsize)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
size of an array: 24
size of each element in array: 8


In [ ]:
import numpy as np
sum_arr=np.arange(100,dtype=np.float32)
sum_arr1=np.sum(sum_arr)
print(sum_arr1)

4950.0


np.zeros make all elements 0
np.ones makes all elements 1
np.full used to all elements you are given one



In [ ]:
zero=np.zeros((2,3))
print(zero)
print(zero.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
float64


In [ ]:
one=np.ones((3,2))
print(one)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
full_arr=np.full((3,2),8)
print(full_arr)

[[8 8]
 [8 8]
 [8 8]]


indexing and slicing in 1d arrays

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[0])
print(arr[-1])
print(arr[1:3])
print(arr[::-1])

1
5
[2 3]
[5 4 3 2 1]


indexing and slicing in 2d arrays


In [ ]:
import numpy as np
arr=np.array([[1,2,3],
             [4,5,6],
             [6,7,8]])
print(arr[0,0])
print(arr[2,2])

1
8


In [ ]:
arr1=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print("slicing in array:",arr1[1:3,0:2])
arr1[1:3,0:2]=[[5,4],[8,7]]
print("modified array:",arr1)

slicing in array: [[4 5]
 [7 8]]
modified array: [[1 2 3]
 [5 4 6]
 [8 7 9]]


boolean indexing (mask)
fancy indexing(selected elements in array using indices)



In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
mask=arr>3
elements=arr[mask]
print(elements)

[4 5 6 7 8 9]


In [ ]:
arr1d=np.array([1,2,3,4,5,6])
indices=[0,2,4]
elements=arr1d[indices]
print(elements)

[1 3 5]


transposing array
swaping in array(swapaxes)



In [ ]:
import numpy as np
arr=np.array([[2,3,4],[5,6,7]])
print(arr.shape)
print(transposed.shape)
transposed=arr.T

print(transposed)

(2, 3)
(3, 2)
[[2 5]
 [3 6]
 [4 7]]


In [ ]:
arr2d=np.array([[1,2,3],
               [4,5,6]])
swap=arr2d.swapaxes(0,1)
print(swap)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr3d=np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[11,22,33],
                [44,55,66],
                [77,88,99]]])
swap=np.swapaxes(arr3d,2,0)
print(arr3d.shape)
print(swap.shape)
print(swap)
print("dimention of array:",arr3d.ndim)
len(swap.shape)==arr3d.ndim

(2, 3, 3)
(3, 3, 2)
[[[ 1 11]
  [ 4 44]
  [ 7 77]]

 [[ 2 22]
  [ 5 55]
  [ 8 88]]

 [[ 3 33]
  [ 6 66]
  [ 9 99]]]
dimention of array: 3


True

sorting and concatenete of array

In [ ]:
import numpy as np
arr=np.array([1,3,6,4,1,3,5])
print(np.sort(arr))

[1 1 3 3 4 5 6]


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.concatenate((a,b)))

[1 2 3 4 5 6]


In [ ]:
import numpy as np
a=np.arange(10)
print(a[a%2==0])
print(a)
print(a[(a>2) & (a<8)])

[0 2 4 6 8]
[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7]


In [ ]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])
print(np.vstack([a1,a2]))
print(np.hstack([a1,a2]))


[[1 1]
 [2 2]
 [3 3]
 [4 4]]
[[1 1 3 3]
 [2 2 4 4]]


In [ ]:
a3=np.arange(1,25).reshape(2,3,4)
print(a3)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
import numpy as np

data=np.array([1,2,3,4])
data1=data*2
print(data1)

[2 4 6 8]


In [ ]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [ ]:
np.ones((3,2))
np.zeros((3,2))
np

NameError: name 'rng' is not defined